# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/danny/alchitry/teensy_spi/cores/fifo_256/fifo_256.xci
# IP: The module: 'fifo_256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/danny/alchitry/teensy_spi/cores/fifo_256/fifo_256.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_256'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/danny/alchitry/teensy_spi/cores/fifo_256/fifo_256_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/danny/alchitry/teensy_spi/cores/fifo_256/fifo_256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/danny/alchitry/teensy_spi/cores/fifo_256/fifo_256.xci
# IP: The module: 'fifo_256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/danny/alchitry/teensy_spi/cores/fifo_256/fifo_256.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/danny/alchitry/teensy_spi/cores/fifo_256/fifo_256_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/danny/alchitry/teensy_spi/cores/fifo_256/fifo_256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
