# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/danny/alchitry/teensy_spi/cores/clk_300mhz/clk_300mhz.xci
# IP: The module: 'clk_300mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/danny/alchitry/teensy_spi/cores/clk_300mhz/clk_300mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_300mhz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/danny/alchitry/teensy_spi/cores/clk_300mhz/clk_300mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_300mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/danny/alchitry/teensy_spi/cores/clk_300mhz/clk_300mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_300mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/danny/alchitry/teensy_spi/cores/clk_300mhz/clk_300mhz.xci
# IP: The module: 'clk_300mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/danny/alchitry/teensy_spi/cores/clk_300mhz/clk_300mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_300mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/danny/alchitry/teensy_spi/cores/clk_300mhz/clk_300mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_300mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/danny/alchitry/teensy_spi/cores/clk_300mhz/clk_300mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_300mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
